GET http://localhost:3001/api/articles

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name": "Slawo",
    "email": "slawo@neuefische.de",
    "password": "ilovemanu"
}

### 
POST http://localhost:3001/api/auth
Content-Type: application/json

{
    "email": "slawo@neuefische.de",
    "password": "ilovemanu"
}

###
POST http://localhost:3000/api/spots
Content-Type: application/json 
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY3YWQ4MmFjZWZlNDMyNGEyMjg2MTgwIn0sImlhdCI6MTYwMTg4NjI3MSwiZXhwIjoxNjAxODg5ODcxfQ.hCSDSqw29LFXmd7HwKgUAqy4WH8zNjwl7nbpJA2gJj8

{
    "title": "micasasasas",
    "description": "adsasdadsasd",
    "latitude": 50,
    "longitude": 8
}

### 